export type RuleSeverity = 'fail' | 'warn' | 'info';
export type RuleGroup =
  | 'schema'
  | 'plugins'
  | 'flows'
  | 'connections'
  | 'alm'
  | 'security'
  | 'capacity'
  | 'webresource';
export type RuleSource = 'Code' | 'Azure Hosted JSON file' | 'Dataverse Entity';
export type RuleEffort = 'low' | 'medium' | 'high';

export interface RuleDefinition {
  id: string;
  title: string;
  description: string;
  group: RuleGroup;
  severity: RuleSeverity;
  source: RuleSource;
  effortToFix: RuleEffort;
  version: string;
  lastUpdated?: Date;
  tags?: string[];
  relatedRules?: string[];
}

export interface RuleEvalResult {
  id: string;
  title: string;
  group: RuleGroup;
  severity: RuleSeverity;
  effortToFix: RuleEffort;
  status: 'finding' | 'pass';
}

export const RULE_GROUP_ORDER: readonly RuleGroup[] = [
  'schema',
  'plugins',
  'flows',
  'connections',
  'alm',
  'security',
  'capacity',
  'webresource',
];

export const RULE_GROUP_LABELS: Record<RuleGroup, string> = {
  schema: 'Schema & Data',
  plugins: 'Plugins & Server-Side Logic',
  flows: 'Power Automate (Flows)',
  connections: 'Connection References & Environment Variables',
  alm: 'ALM & Layering',
  security: 'Security Model',
  capacity: 'Capacity & Governance',
  webresource: 'Web Resources',
};

export const RULES: readonly RuleDefinition[] = [
  // ── Schema & Data ────────────────────────────────────────────────────────────
  {
    id: 'SCH-IDX-001',
    title: 'Missing index on frequently filtered column',
    description: 'Flags columns used in view or FetchXML filters that have no supporting index on the table.',
    group: 'schema',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['performance', 'index', 'query', 'FetchXML', 'optimization'],
    relatedRules: ['SCH-CASCADE-010', 'CAP-API-001'],
  },
  {
    id: 'SCH-OPT-002',
    title: 'Choice (option set) sprawl',
    description: 'Flags choice columns with more options than the configured threshold, indicating likely misuse as a lookup proxy.',
    group: 'schema',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['schema', 'choice', 'option-set', 'design', 'data-model'],
    relatedRules: ['SCH-OPT-003', 'SCH-COL-004'],
  },
  {
    id: 'SCH-OPT-003',
    title: 'Duplicate global choices',
    description: 'Detects pairs of global choice sets with near-identical option values, suggesting accidental duplication instead of reuse.',
    group: 'schema',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['schema', 'choice', 'option-set', 'duplication', 'design'],
    relatedRules: ['SCH-OPT-002'],
  },
  {
    id: 'SCH-COL-004',
    title: 'Orphaned/unused column (near-zero population)',
    description: 'Flags columns where fewer than a configurable percentage of records have a non-null value, suggesting the column is no longer in use.',
    group: 'schema',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['schema', 'unused', 'cleanup', 'data-quality', 'maintenance'],
    relatedRules: ['SCH-DESC-008', 'WR-UNUSED-001'],
  },
  {
    id: 'SCH-NN-005',
    title: 'Unbounded N:N intersect table growth',
    description: 'Flags many-to-many intersect tables that have grown beyond a threshold without an archival or cleanup strategy.',
    group: 'schema',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['schema', 'relationship', 'many-to-many', 'performance', 'capacity'],
    relatedRules: ['CAP-STORE-002', 'SCH-CASCADE-010'],
  },
  {
    id: 'SCH-AUDIT-006',
    title: 'Audit log growth rate vs. retention policy',
    description: 'Flags environments where audit log creation volume exceeds the acceptable monthly growth threshold relative to the configured retention period.',
    group: 'schema',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['audit', 'governance', 'capacity', 'retention', 'compliance'],
    relatedRules: ['CAP-STORE-002', 'CAP-FILE-004'],
  },
  {
    id: 'SCH-LOOKUP-007',
    title: 'Excessive lookup columns on one table',
    description: 'Flags tables with an unusually high count of lookup columns, signalling denormalization debt.',
    group: 'schema',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['schema', 'lookup', 'denormalization', 'design', 'data-model'],
    relatedRules: ['SCH-COL-004', 'SCH-NN-005'],
  },
  {
    id: 'SCH-DESC-008',
    title: 'Missing display name or description on custom table/column',
    description: 'Flags custom tables or columns with a missing or empty description, removing the only in-product documentation for that component.',
    group: 'schema',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['documentation', 'metadata', 'schema', 'quality', 'governance'],
    relatedRules: ['SCH-PREFIX-009', 'ALM-PUB-005'],
  },
  {
    id: 'SCH-PREFIX-009',
    title: 'Publisher prefix convention violation',
    description: "Flags custom solution components whose logical names do not begin with the organisation's registered publisher prefix.",
    group: 'schema',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['naming', 'convention', 'publisher', 'ALM', 'schema'],
    relatedRules: ['ALM-PUB-005', 'SCH-DESC-008'],
  },
  {
    id: 'SCH-CASCADE-010',
    title: 'Cascade delete on high-volume relationship',
    description: 'Flags 1:N relationships configured with cascade delete where the child table has a high record count, risking long-running platform timeouts.',
    group: 'schema',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['performance', 'cascade', 'delete', 'relationship', 'risk'],
    relatedRules: ['SCH-IDX-001', 'SCH-NN-005'],
  },

  // ── Plugins & Server-Side Logic ───────────────────────────────────────────────
  {
    id: 'PLG-SYNC-001',
    title: 'Synchronous plugin on high-volume message',
    description: 'Flags synchronous plugin steps on Create or Update messages for tables with high recent transaction volume.',
    group: 'plugins',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['plugin', 'performance', 'synchronous', 'transaction', 'latency'],
    relatedRules: ['PLG-DUP-002', 'PLG-BROAD-003'],
  },
  {
    id: 'PLG-DUP-002',
    title: 'Duplicate plugin step registrations',
    description: 'Detects multiple plugin steps registered on the same message, entity, and stage combination.',
    group: 'plugins',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['plugin', 'registration', 'duplicate', 'configuration', 'reliability'],
    relatedRules: ['PLG-SYNC-001', 'PLG-BROAD-003'],
  },
  {
    id: 'PLG-BROAD-003',
    title: 'Plugin registered on overly broad message set',
    description: 'Flags plugin assemblies registered against an unusually high number of distinct messages or entities.',
    group: 'plugins',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['plugin', 'registration', 'performance', 'scope', 'configuration'],
    relatedRules: ['PLG-SYNC-001', 'PLG-DUP-002'],
  },
  {
    id: 'PLG-IMG-004',
    title: 'Plugin step missing pre/post image',
    description: 'Flags plugin steps whose registration omits a pre- or post-image that the plugin code appears to access.',
    group: 'plugins',
    severity: 'info',
    source: 'Code',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['plugin', 'image', 'configuration', 'reliability', 'data'],
    relatedRules: ['PLG-RETRY-005'],
  },
  {
    id: 'PLG-RETRY-005',
    title: 'No exception handling in plugin',
    description: 'Flags plugin steps where configuration metadata suggests no structured exception handling is in place.',
    group: 'plugins',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['plugin', 'exception-handling', 'reliability', 'error', 'resilience'],
    relatedRules: ['PLG-IMG-004', 'FLOW-ERR-002'],
  },

  // ── Power Automate (Flows) ────────────────────────────────────────────────────
  {
    id: 'FLOW-OWN-001',
    title: 'Flow owned by individual user',
    description: 'Flags cloud flows owned by a named human user account rather than a service or application account.',
    group: 'flows',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'ownership', 'ALM', 'service-account', 'governance'],
    relatedRules: ['FLOW-CONN-007', 'ALM-CREF-001'],
  },
  {
    id: 'FLOW-ERR-002',
    title: 'Flow with no configured error handling',
    description: 'Flags flows where no action has a run-after path set for failed, skipped, or timed-out outcomes.',
    group: 'flows',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'error-handling', 'reliability', 'resilience', 'quality'],
    relatedRules: ['FLOW-TRIG-006', 'PLG-RETRY-005'],
  },
  {
    id: 'FLOW-API-003',
    title: 'Flow approaching API request entitlement limit',
    description: "Flags flows whose recent run volume is trending toward the daily API request entitlement for the owning user or environment.",
    group: 'flows',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'API', 'capacity', 'licensing', 'throttling'],
    relatedRules: ['CAP-API-001', 'FLOW-LOOP-005'],
  },
  {
    id: 'FLOW-DIS-004',
    title: 'Flow disabled or in suspended/failed state',
    description: 'Flags cloud flows currently in a suspended or manually disabled state, meaning the business process they implement is silently not running.',
    group: 'flows',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'health', 'monitoring', 'reliability', 'operations'],
    relatedRules: ['FLOW-ERR-002', 'FLOW-TRIG-006'],
  },
  {
    id: 'FLOW-LOOP-005',
    title: 'Dataverse action called in a loop instead of batch',
    description: 'Flags flows that call a Dataverse Create, Update, or Delete action inside an Apply-to-each or Do-until loop instead of using a batch request.',
    group: 'flows',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'performance', 'batch', 'optimization', 'API'],
    relatedRules: ['FLOW-API-003', 'CAP-API-001'],
  },
  {
    id: 'FLOW-TRIG-006',
    title: 'Recursive trigger-condition risk',
    description: 'Flags flows that update the same table they are triggered by with no trigger condition guarding against infinite re-triggering.',
    group: 'flows',
    severity: 'fail',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'trigger', 'recursive', 'infinite-loop', 'risk'],
    relatedRules: ['FLOW-ERR-002', 'FLOW-DIS-004'],
  },
  {
    id: 'FLOW-CONN-007',
    title: 'Flow using a personal (non-shared) connection',
    description: 'Flags flows using a personal connection authenticated as an individual user rather than a shared service account connection.',
    group: 'flows',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['flow', 'connection', 'service-account', 'ALM', 'governance'],
    relatedRules: ['FLOW-OWN-001', 'ALM-CREF-001'],
  },

  // ── Connection References & Environment Variables ─────────────────────────────
  {
    id: 'ALM-CREF-001',
    title: 'Flow using a hardcoded connection instead of a connection reference',
    description: 'Flags flows whose JSON definition references a connector directly by path rather than via a solution-aware connection reference component.',
    group: 'connections',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'connection-reference', 'deployment', 'portability', 'flow'],
    relatedRules: ['ALM-ENV-002', 'FLOW-CONN-007'],
  },
  {
    id: 'ALM-ENV-002',
    title: 'Environment variable with no default value',
    description: 'Flags environment variable definitions with no default value, which causes null values or import failures when deployed to a new environment.',
    group: 'connections',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'environment-variable', 'deployment', 'configuration', 'portability'],
    relatedRules: ['ALM-CREF-001', 'ALM-SECRET-003'],
  },
  {
    id: 'ALM-SECRET-003',
    title: 'Secret stored as plain-text environment variable',
    description: "Flags String-type environment variables whose schema name matches common secret-related patterns, indicating unencrypted storage of sensitive values.",
    group: 'connections',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'secret', 'environment-variable', 'compliance', 'sensitive-data'],
    relatedRules: ['ALM-ENV-002', 'SEC-ROLE-003'],
  },
  {
    id: 'ALM-CREF-004',
    title: 'Connection reference unused by any solution component',
    description: 'Flags connection references present in the solution that are not referenced by any active flow or other component.',
    group: 'connections',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'connection-reference', 'unused', 'cleanup', 'maintenance'],
    relatedRules: ['ALM-CREF-001', 'WR-UNUSED-001'],
  },

  // ── ALM & Layering ────────────────────────────────────────────────────────────
  {
    id: 'ALM-LAYER-001',
    title: 'Unmanaged customization layer in non-DEV environment',
    description: 'Flags the presence of visible unmanaged solution layers in any environment configured as non-DEV.',
    group: 'alm',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'layering', 'managed', 'unmanaged', 'deployment'],
    relatedRules: ['ALM-LAYER-002', 'ALM-DEP-004'],
  },
  {
    id: 'ALM-LAYER-002',
    title: 'Managed solution components have active unmanaged override layer',
    description: 'Flags managed solution components that have an unmanaged customization layer sitting on top, risking conflict or silent loss on the next managed upgrade.',
    group: 'alm',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'layering', 'managed', 'override', 'upgrade-risk'],
    relatedRules: ['ALM-LAYER-001', 'ALM-DEP-004'],
  },
  {
    id: 'ALM-SEG-003',
    title: 'Single solution with excessive component count',
    description: 'Flags solutions that have grown beyond a component-count threshold without segmentation into a core/extension pattern.',
    group: 'alm',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'solution-segmentation', 'architecture', 'design', 'maintainability'],
    relatedRules: ['ALM-LAYER-001', 'ALM-DEP-004'],
  },
  {
    id: 'ALM-DEP-004',
    title: 'Missing or broken component dependency',
    description: 'Flags solution components that declare a dependency on another component absent from the current environment, causing import failures on deployment.',
    group: 'alm',
    severity: 'fail',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'dependency', 'import', 'deployment', 'reliability'],
    relatedRules: ['ALM-LAYER-001', 'ALM-LAYER-002'],
  },
  {
    id: 'ALM-PUB-005',
    title: 'Solution using default Microsoft publisher',
    description: 'Flags solutions still associated with the default Microsoft publisher rather than a custom organisational publisher, leaving components with no namespace isolation.',
    group: 'alm',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['ALM', 'publisher', 'naming', 'convention', 'namespace'],
    relatedRules: ['SCH-PREFIX-009', 'ALM-SEG-003'],
  },

  // ── Security Model ────────────────────────────────────────────────────────────
  {
    id: 'SEC-ADMIN-001',
    title: 'Excessive System Administrator role assignments',
    description: 'Flags environments where more than the recommended number of users hold the System Administrator security role.',
    group: 'security',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'admin', 'role', 'privilege', 'governance'],
    relatedRules: ['SEC-ROLE-003', 'SEC-BU-005'],
  },
  {
    id: 'SEC-TEAM-002',
    title: 'Excessive ad hoc (non-AAD-backed) owner teams',
    description: 'Flags environments with a high count of owner teams not backed by an Azure Active Directory security group, requiring manual membership lifecycle management.',
    group: 'security',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'team', 'Azure-AD', 'governance', 'lifecycle'],
    relatedRules: ['SEC-ADMIN-001', 'SEC-BU-005'],
  },
  {
    id: 'SEC-ROLE-003',
    title: 'Security role granting org-wide access on sensitive table',
    description: 'Flags security roles that grant Organisation-level read or write privilege on tables designated as sensitive in the configuration.',
    group: 'security',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'role', 'privilege', 'sensitive-data', 'access-control'],
    relatedRules: ['SEC-ADMIN-001', 'SEC-FLS-004'],
  },
  {
    id: 'SEC-FLS-004',
    title: 'Field security profile defined but assigned to nobody',
    description: 'Flags field security profiles that exist in the environment but have no team or user assigned, leaving the protected fields effectively unprotected.',
    group: 'security',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'field-level-security', 'profile', 'access-control', 'configuration'],
    relatedRules: ['SEC-ROLE-003', 'SEC-BU-005'],
  },
  {
    id: 'SEC-BU-005',
    title: 'Record sharing volume suggests missing business unit design',
    description: 'Flags environments with high explicit record-sharing volume relative to a shallow business unit hierarchy, indicating the security model was not designed to match actual access patterns.',
    group: 'security',
    severity: 'info',
    source: 'Code',
    effortToFix: 'high',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'business-unit', 'sharing', 'design', 'access-control'],
    relatedRules: ['SEC-ADMIN-001', 'SEC-TEAM-002'],
  },

  // ── Capacity & Governance ─────────────────────────────────────────────────────
  {
    id: 'CAP-API-001',
    title: 'API request consumption trending toward entitlement cap',
    description: 'Flags environments where API request consumption is trending above a configurable percentage of the licensed daily entitlement.',
    group: 'capacity',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['capacity', 'API', 'licensing', 'throttling', 'performance'],
    relatedRules: ['FLOW-API-003', 'FLOW-LOOP-005'],
  },
  {
    id: 'CAP-STORE-002',
    title: 'Database storage consumption trending toward allocation',
    description: 'Flags environments where database storage consumption exceeds a configurable percentage of the allocated capacity.',
    group: 'capacity',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['capacity', 'storage', 'database', 'governance', 'growth'],
    relatedRules: ['SCH-AUDIT-006', 'CAP-FILE-004'],
  },
  {
    id: 'CAP-DLP-003',
    title: 'DLP policy mixing Business and Non-Business connector groups',
    description: 'Flags DLP policies where Business and Non-Business classified connectors are placed in the same group, eliminating data loss prevention protection.',
    group: 'capacity',
    severity: 'fail',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['security', 'DLP', 'governance', 'compliance', 'connectors'],
    relatedRules: ['ALM-SECRET-003', 'SEC-ROLE-003'],
  },
  {
    id: 'CAP-FILE-004',
    title: 'File/attachment storage consumption trending toward allocation',
    description: 'Flags environments where file and attachment storage consumption exceeds a configurable percentage of the allocated capacity.',
    group: 'capacity',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['capacity', 'storage', 'file', 'attachment', 'growth'],
    relatedRules: ['CAP-STORE-002', 'SCH-AUDIT-006'],
  },

  // ── Web Resources ─────────────────────────────────────────────────────────────
  {
    id: 'WR-UNUSED-001',
    title: 'Web resource not referenced by any solution component',
    description: 'Flags web resources present in the solution that are not referenced by any form, ribbon, site map, or other active component.',
    group: 'webresource',
    severity: 'info',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['web-resource', 'unused', 'cleanup', 'maintenance', 'size'],
    relatedRules: ['WR-SIZE-002', 'SCH-COL-004'],
  },
  {
    id: 'WR-SIZE-002',
    title: 'Web resource exceeds size threshold or is unminified',
    description: 'Flags JavaScript or CSS web resources exceeding a size threshold or showing clear signs of being unminified, increasing form load time for all users.',
    group: 'webresource',
    severity: 'warn',
    source: 'Azure Hosted JSON file',
    effortToFix: 'low',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['web-resource', 'performance', 'size', 'JavaScript', 'CSS'],
    relatedRules: ['WR-UNUSED-001', 'WR-LIB-004'],
  },
  {
    id: 'WR-API-003',
    title: 'Web resource using deprecated Xrm client API',
    description: 'Flags JavaScript web resources that reference Xrm client API namespaces or methods that Microsoft has formally deprecated.',
    group: 'webresource',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['web-resource', 'JavaScript', 'deprecated', 'API', 'compatibility'],
    relatedRules: ['WR-LIB-004', 'WR-SIZE-002'],
  },
  {
    id: 'WR-LIB-004',
    title: 'Outdated third-party JavaScript library',
    description: 'Flags JavaScript web resources embedding a recognisable third-party library at a version older than the configured minimum.',
    group: 'webresource',
    severity: 'warn',
    source: 'Code',
    effortToFix: 'medium',
    version: '1.0.0.0',
    lastUpdated: new Date('2026-06-23'),
    tags: ['web-resource', 'JavaScript', 'library', 'security', 'outdated'],
    relatedRules: ['WR-API-003', 'WR-SIZE-002'],
  },
];
